spring:
  application:
    name: chat-server
  datasource:
    url: jdbc:h2:file:./data/chatdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:sql/create.db.schema.sql
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: chat_server
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080